apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-management-deployment
  namespace: ctse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-management
  template:
    metadata:
      labels:
        app: order-management
    spec:
      containers:
        - name: order-management
          image: it19155944/orders-management:latest
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: order-management-config
