apiVersion: v1
kind: Service
metadata:
  namespace: ctse
  name: order-management-service
spec:
  selector:
    app: order-management
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: LoadBalancer
  publishNotReadyAddresses: true
